const CONFIG = {
  version: '1.1.5',
  downloadUrl: 'https://github.com/JunTembMoon/ROVTOR/raw/refs/heads/main/files/ROVTOR%20Setup%201.1.5.exe',
  githubUrl: 'https://github.com/JunTembMoon/ROVTOR',
  releaseNotes: [
    ['스크린샷 캔버스', '이미지 위에 채팅을 올리고, 보이는 자리에서 바로 다듬습니다.'],
    ['복붙 해석기', '색상 코드와 행동 포맷을 붙이면, ROVTOR는 “알겠습니다”라고 합니다.'],
    ['좌표 대신 흐름', '숫자 1px과 싸우는 시간을 줄이고 캐릭터에게 돌려드립니다.'],
    ['WORLD MODE', 'SAMP 시절 고고학은 여기까지. GTA:WORLD급 작업 흐름으로 전환합니다.'],
    ['LSRP+ 대응', '구식 클릭 지옥과의 호환성은 없습니다. 더 좋은 쪽으로 왔으니까요.']
  ]
};

const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];
let lastFocus;

function showToast(title, text) { $('#toastTitle').textContent = title; $('#toastText').textContent = text; $('.toast').classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => $('.toast').classList.remove('show'), 4600); }
function validUrl(url) { return url && !url.includes('YOUR_'); }
function useLink(type) { const url = type === 'github' ? CONFIG.githubUrl : CONFIG.downloadUrl; if (validUrl(url)) window.location.href = url; else showToast(type === 'github' ? 'GitHub 링크 준비 중' : '다운로드 링크 준비 중', '링크가 곧 추가됩니다. 조금만 기다려주세요!'); }

function modal(open) { const el = $('#launchModal'); if (open) { lastFocus = document.activeElement; el.classList.add('open'); document.body.style.overflow = 'hidden'; $('.modal-confirm').focus(); } else { el.classList.remove('open'); document.body.style.overflow = ''; lastFocus?.focus(); } }
function initModal() { const el = $('#launchModal'), seen = localStorage.getItem('rovtor-release-115-seen'); if (!seen) setTimeout(() => modal(true), 450); $('.modal-close').onclick = () => modal(false); $('.modal-confirm').onclick = () => { localStorage.setItem('rovtor-release-115-seen', '1'); modal(false); }; $('.modal-explore').onclick = () => { localStorage.setItem('rovtor-release-115-seen', '1'); modal(false); $('#release').scrollIntoView({behavior:'smooth'}); }; el.onclick = e => { if (e.target === e.currentTarget) modal(false); }; document.addEventListener('keydown', e => { if (!el.classList.contains('open')) return; if (e.key === 'Escape') return modal(false); if (e.key !== 'Tab') return; const focusables = $$('button', el), current = focusables.indexOf(document.activeElement), next = e.shiftKey ? current - 1 : current + 1; if (next < 0 || next >= focusables.length) { e.preventDefault(); focusables[(next + focusables.length) % focusables.length].focus(); } }); }
function initNavigation() { const header = $('.site-header'), progress = $('.progress i'), top = $('.to-top'); let scheduled = false; const update = () => { const y = scrollY, total = document.documentElement.scrollHeight - innerHeight; header.classList.toggle('scrolled', y > 30); top.classList.toggle('show', y > 600); progress.style.width = `${total ? y / total * 100 : 0}%`; scheduled = false; }; window.addEventListener('scroll', () => { if (!scheduled) { scheduled = true; requestAnimationFrame(update); } }, {passive:true}); update(); top.onclick = () => scrollTo({top:0,behavior:'smooth'}); const toggle = $('.menu-toggle'), nav = $('.site-header nav'); toggle.onclick = () => { const open = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded', open); }; $$('nav a').forEach(a => a.onclick = () => nav.classList.remove('open')); }
function initActiveNav() { const links = $$('.site-header nav a'); const activate = id => links.forEach(link => link.classList.toggle('active', link.getAttribute('href') === `#${id}`)); activate('home'); const targets = links.map(link => $(link.getAttribute('href'))).filter(target => target && target.id !== 'home'); const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) activate(entry.target.id); }), {rootMargin:'-38% 0px -54% 0px',threshold:0}); targets.forEach(target => observer.observe(target)); }
function initReveal() { const observer = new IntersectionObserver(entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); observer.unobserve(e.target); } }), {threshold:.12}); $$('.reveal').forEach(e => observer.observe(e)); }
function initEditor() { const typed = $('.typing-text'); if (typed) { const text = typed.textContent; typed.textContent = ''; let index = 0; const type = () => { if (index <= text.length) { typed.textContent = text.slice(0,index++); setTimeout(type, 42); } }; setTimeout(type, 1250); } $('.load-shot')?.addEventListener('click', () => showToast('스크린샷 불러오기', '실제 프로그램에서는 여기서 이미지 파일을 선택합니다.')); }
function initGuiControls() { const panel = $('.control-panel'), chat = $('.sample-chat'); if (!panel || !chat) return; const ranges = $$('input[type="range"]', panel), outputs = $$('output', panel), checks = $$('input[type="checkbox"]', panel); const specs = [{min:-80,max:80,value:0,unit:'px'},{min:0,max:140,value:70,unit:'px'},{min:12,max:36,value:22,unit:'px'},{min:0,max:8,value:5,unit:'px'}], clamp = (value,min,max) => Math.min(max,Math.max(min,value)); ranges.forEach((range,index) => Object.assign(range,specs[index])); const render = () => { outputs.forEach((output,index) => output.textContent = `${ranges[index].value}${specs[index].unit}`); const x = Number(ranges[0].value), y = Number(ranges[1].value) - 70; chat.style.setProperty('--chat-x', `${x}px`); chat.style.setProperty('--chat-y', `${y}px`); chat.style.transform = `translate(${x}px, ${y}px)`; chat.style.fontSize = `${ranges[2].value}px`; chat.style.webkitTextStroke = `${ranges[3].value}px #05070a`; }; ranges.forEach(range => range.addEventListener('input', render)); render(); checks[0]?.addEventListener('change', () => chat.classList.toggle('chat-regular', !checks[0].checked)); checks[1]?.addEventListener('change', () => chat.classList.toggle('chat-no-time', !checks[1].checked)); let drag; chat.addEventListener('pointerdown', event => { drag = {id:event.pointerId,x:event.clientX,y:event.clientY,startX:Number(ranges[0].value),startY:Number(ranges[1].value)}; chat.setPointerCapture(event.pointerId); chat.classList.add('chat-dragging'); }); chat.addEventListener('pointermove', event => { if (!drag || drag.id !== event.pointerId) return; ranges[0].value = clamp(drag.startX + event.clientX - drag.x, specs[0].min, specs[0].max); ranges[1].value = clamp(drag.startY + event.clientY - drag.y, specs[1].min, specs[1].max); render(); }); const endDrag = event => { if (!drag || drag.id !== event.pointerId) return; drag = null; chat.classList.remove('chat-dragging'); }; chat.addEventListener('pointerup', endDrag); chat.addEventListener('pointercancel', endDrag); $$('[data-mock-action]').forEach(button => button.addEventListener('click', () => { const action = button.dataset.mockAction; if (action === 'chat') { chat.classList.remove('chat-selected'); void chat.offsetWidth; chat.classList.add('chat-selected'); showToast('채팅 레이어 선택됨', '드래그와 슬라이더로 바로 배치할 수 있습니다.'); } else showToast('PNG 내보내기 준비 완료', '실제 프로그램에서는 완성된 채팅 PNG를 저장합니다.'); })); }
function initGuiReset() { const panel = $('.control-panel'); if (!panel) return; const title = $$('.control-title', panel)[1], ranges = $$('input[type="range"]', panel); if (!title || ranges.length < 2) return; const reset = document.createElement('button'); reset.type = 'button'; reset.className = 'mock-reset'; reset.textContent = '↺ 초기화'; title.append(reset); reset.addEventListener('click', () => { ranges[0].value = 0; ranges[1].value = 70; ranges[0].dispatchEvent(new Event('input', {bubbles:true})); showToast('채팅 위치 초기화', '기본 위치로 다시 돌렸습니다.'); }); }
function initDemo() { const output = $('#demoOutput'), section = $('.color-demo'); if (!output || !section) return; let action = '*행동', color = '#ff9d4d', cycleTimer, visible = false, stageTimers = []; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches, lines = [['[22:57:53]', 'jacket 안에서 휴대폰을 꺼냅니다.'], ['[22:57:56]', '화면이 밝게 켜진다.'], ['[22:57:58]', 'unread messages를 확인한다.']], followUps = ['/do', '/me']; const markup = () => `<div class="paste-document">${lines.map(([time,text], i) => `<p class="paste-line" style="--line-delay:${i * 150}ms"><b>${time}</b> <strong style="color:${color}">${i === 0 ? action : followUps[i - 1]}</strong> ${text}</p>`).join('')}</div>`; const stop = () => { clearTimeout(cycleTimer); stageTimers.forEach(clearTimeout); stageTimers = []; }; const paint = () => { output.classList.remove('deleting'); output.innerHTML = markup(); if (reduced) return; stageTimers.push(setTimeout(() => { const copies = document.createElement('div'); copies.className = 'paste-copies'; copies.innerHTML = '<span>PASTE × 12</span><span>PASTE × 24</span><span>PASTE × 48</span>'; output.append(copies); }, 980), setTimeout(() => output.classList.add('deleting'), 2050), setTimeout(() => { output.innerHTML = '<span class="paste-empty">다시 복붙할 준비 완료.</span>'; output.classList.remove('deleting'); }, 2740)); }; const loop = () => { if (!visible || reduced) return; stop(); paint(); cycleTimer = setTimeout(loop, 3000); }; const restart = () => { if (reduced) paint(); else if (visible) loop(); }; $$('.demo-action').forEach(b => b.onclick = () => { action = b.dataset.demo.trim(); $$('.demo-action').forEach(x => { x.classList.toggle('active', x === b); x.setAttribute('aria-pressed', x === b); }); restart(); }); $$('.demo-color').forEach(b => b.onclick = () => { color = b.dataset.demoColor; restart(); }); if (reduced) return paint(); const observer = new IntersectionObserver(entries => { visible = entries[0].isIntersecting; if (visible) loop(); else stop(); }, {threshold:.12}); observer.observe(section); }
function initMeters() { $$('.meter, .benchmark').forEach(target => { const observer = new IntersectionObserver(entries => { if(entries[0].isIntersecting) { target.classList.add('animated'); observer.disconnect(); } },{threshold:.35}); observer.observe(target); }); }
function renderNotes() { $('#releaseCards').innerHTML = CONFIG.releaseNotes.map(([title,text], i) => `<article class="release-card"><b>0${i+1} / ${title}</b><p>${text}</p></article>`).join(''); }
function initActions() { $$('.js-download').forEach(b => b.addEventListener('click', () => useLink('download'))); $$('.js-github').forEach(b => b.addEventListener('click', () => useLink('github'))); $('.toast-close').onclick = () => $('.toast').classList.remove('show'); }
function initRipples() { $$('.button, .download-button, .header-download, .bro-link a').forEach(button => button.addEventListener('pointerdown', event => { const rect = button.getBoundingClientRect(), ripple = document.createElement('i'); ripple.className = 'click-ripple'; ripple.style.left = `${event.clientX - rect.left}px`; ripple.style.top = `${event.clientY - rect.top}px`; button.append(ripple); ripple.addEventListener('animationend', () => ripple.remove()); })); }
function initLegacyExcuses() { const button = $('.legacy-excuse'), response = $('.legacy-response'), rovtor = $('.rovtor-response'); if (!button || !response || !rovtor) return; const rounds = [['LSRP+: “한 번 더 저장해 보세요. 이번에는 우주가 도와줄 수도 있습니다.”', 'ROVTOR: “저장은 됐고, 이제 RP 하세요.”'], ['LSRP+: “레이아웃은 자유롭습니다. 너무 자유로워서 사용자가 길을 잃습니다.”', 'ROVTOR: “필요한 건 처음부터 눈앞에 있습니다.”'], ['LSRP+: “문제 없습니다. 단지 텍스트가 다른 삶을 선택했을 뿐입니다.”', 'ROVTOR: “텍스트는 여기 있고, 바로 움직입니다.”'], ['LSRP+: “클릭은 운동입니다. 오늘의 목표는 12회입니다.”', 'ROVTOR: “클릭은 한 번이면 충분합니다.”'], ['LSRP+: “이 기능은 추억 속에서 지원합니다.”', 'ROVTOR: “추억 말고 지금 작업을 지원합니다.”']]; let index = -1; button.addEventListener('click', () => { index = (index + 1) % rounds.length; [response, rovtor].forEach((element, position) => { element.textContent = rounds[index][position]; element.classList.remove('swap'); void element.offsetWidth; element.classList.add('swap'); }); }); }
function initRoveEasterEgg() { if (matchMedia('(prefers-reduced-motion: reduce)').matches) return; const section = $('#developer'), overlay = $('.rove-overlay'); if (!section || !overlay) return; const observer = new IntersectionObserver(entries => { if (!entries[0].isIntersecting) return; observer.disconnect(); setTimeout(() => { overlay.classList.add('party'); setTimeout(() => { overlay.classList.remove('party'); overlay.classList.add('sorry'); setTimeout(() => overlay.classList.remove('sorry'), 950); }, 2000); }, 1000); }, {threshold:.45}); observer.observe(section); }
renderNotes(); initModal(); initNavigation(); initActiveNav(); initReveal(); initEditor(); initGuiControls(); initGuiReset(); initDemo(); initMeters(); initActions(); initRipples(); initLegacyExcuses(); initRoveEasterEgg();
